### ISSUE TITLE
keystore

### ISSUE THREAD

**Issue by IzzySoft** [jkas-dbt/AndroidPE#1]
Looks like you've made your entire keystore public by checking it into this repo – and moreover also [published all credentials](https://github.com/jkas-dbt/AndroidPE/blob/6fcf0e5822263e5d23a2379f0163833fa874c48e/app/build.gradle#L11-L20) – so your signing is no longer secure as it all must be counted as compromised.

Which means you'll need a new keystore and fresh passwords – but without putting them into your repo again. Else anyone could use your code, add some malware to it, sign the APK with your key and publish it – and whoever updates to that one (which would be accepted as it's properly signed with your key) will be infected. So please take urgent action!

**Comment by jkas-dbt** [comment]
Thanks for pointing that out. I didn't even think about it for a second.
